### ISSUE TITLE
Supported node version

### ISSUE THREAD

**Issue by pbarbiero** [ianstormtaylor/superstruct#82]
Which versions of node are supported? Currently due to dependencies only node 8+ is  supported, is that intended?

`error shallow-clone@2.0.2: The engine "node" is incompatible with this module. Expected version ">=8".`

**Comment by ianstormtaylor** [comment]
@jonschlinkert I think the `engines.node` version was changed in a patch release of `shallow-clone`? Was that by mistake? It seems like something that might require a major release since it breaks backwards compat for things that were depending on it before. What do you think?

Seems like we'll have to pin `shallow-clone` to an earlier patch.

**Comment by pbarbiero** [comment]
Yeah, looking at the 'shallow-deep' repo yields very little info. What's confusing is clone-deep specifically calls out 0.10 >= but that change to shallow-clone in 2.0.1 breaks that entirely.

It seems like a pin to 2.0.0 is required to make it work in earlier versions. I wonder if its best to pin to the last `clone-deep` 1.x.x release instead just to be safe, or investigate a different alternative dependency to cover that need, one that has guaranteed compatibility for node 4 (or atleast node 6) and up.

**Comment by ianstormtaylor** [comment]
@pbarbiero I think we can get away for now with just pinning the `shallow-clone` in our package.json, and it should pick that up for the sub-dependency. If you want to make that PR that would be great!

**Comment by jonschlinkert** [comment]
Might have been an oversight. I’ll check first thing in the morning. Thx for the heads up

**Comment by jonschlinkert** [comment]
I should have bumped clone-deep to 3.0.0, not 2.0.1.  That wasn't intentional, I'm usually very conservative about versioning, my apologies for the trouble this caused. 

I'm going to revert the dep upgrade in clone-deep, publish 2.0.2 to fix the issue, then publish 3.0.0 with the dep upgrade.

**Comment by jonschlinkert** [comment]
should be fixed, sorry it took me so long

**Comment by pbarbiero** [comment]
Hi @jonschlinkert 

npm is still showing the latest v2 release of clone-deep at 2.0.1, with shallow-clone at ^2.0.0. Can you publish clone-deep 2.0.2 with shallow-clone pinned to exactly 2.0.0?

**Comment by doowb** [comment]
@pbarbiero @ianstormtaylor I just spoke with Jon. He's had a lot of meetings to get to and was in a hurry and forgot to publish 2.0.2. I'm going to get it published in a few minutes.

**Comment by doowb** [comment]
I published 2.0.2. I think I got it right :) let me know if anything seems wrong.

**Comment by jonschlinkert** [comment]
thanks @doowb! (it was just one meeting, I had to do a pitch... sorry I dropped the ball on this)

**Comment by pbarbiero** [comment]
Fix confirmed! Thanks guys.
